package com.example.gymmanagement.global

object SqlTable {
    const val admin = "CREATE TABLE ADMIN(ID INTEGER PRIMARY KEY AUTOINCREMENT, USER_NAME TEXT DEFAULT ''," + "PASSWORD TEXT DEFAULT '', MOBLIE TEXT DEFAULT '')"

    const val member = "CREATE TABLE MEMBER(ID INTEGER PRIMARY KEY AUTOINCREMENT, FIRST_NAME TEXT DEFAULT '', LAST_NAME TEXT DEFAULT '', "+
            "GENDER TEXT DEFAULT '', AGE TEXT DEFAULT '', WEIGHT TEXT DEFAULT '', MOBLIE TEXT DEFAULT '', ADDRESS TEXT DEFAULT '',"+
            "IMAGE_PATH TEXT DEFAULT '')"
}